name: Focus To Evolve
favicon: null
layout_spectrum: 0.7388675028923899
typography_spectrum: 0.7328345221467316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1978134592063725
  lightness: 0.5299064628779888
  saturation: 0.0065956751350313425
  rhythmicContrast: 0.9958921167999506
purpose: []
