name: Focus To Evolve
favicon: null
layout_spectrum: 0.72435
typography_spectrum: 0.7328345221467316
title: Focus To Evolve
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b2654'
    - '#434343'
    - '#747474'
    - '#dedede'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.0065956751350313425
  rhythmicContrast: 1
purpose: []
